In [1]:
#untuk memulai numpty kita perlu mengimportnya
import numpy as np

In [2]:
data = [1,2,3] #data list pada python
data

[1, 2, 3]

In [3]:
np.array(data) #list di convert ke dalam array numpy

array([1, 2, 3])

In [4]:
#membuat data array numpy otomatis
np.arange(0,10) # 0 adalah batas awal dan 10 batas akhir

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,10,2) # 2 di belakang adalah kelipatan

array([0, 2, 4, 6, 8])

In [6]:
#Membuat array Dummy
np.linspace(0,10,3) # 0 adalah batas awalnya, 10 adalah batas akhir dan 3 adalah jumlah array dummy

array([ 0.,  5., 10.])

In [7]:
np.linspace(0,10,50) # semakin banyak jumlah arraynya maka semakin banyak pula komanya

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [8]:
np.random.rand(3) #Membuat data array random kolom 3

array([0.72499894, 0.33331139, 0.96800532])

In [11]:
np.random.rand(3,4)#Membuat data array random 3 baris 4 kolom

array([[0.22351544, 0.66474889, 0.67436754, 0.80601988],
       [0.39845938, 0.65889017, 0.2555341 , 0.22472114],
       [0.36906153, 0.93439017, 0.39465393, 0.06992818]])